// Mocks generated by Mockito 5.4.4 from annotations
// in tractian_test/test/models/data_loader_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tractian_test/models/asset/asset.dart' as _i4;
import 'package:tractian_test/models/data/data_loader.dart' as _i2;
import 'package:tractian_test/models/location/location.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DataLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataLoader extends _i1.Mock implements _i2.DataLoader {
  MockDataLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Asset>> loadUnlinkedAssets(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadUnlinkedAssets,
          [path],
        ),
        returnValue: _i3.Future<List<_i4.Asset>>.value(<_i4.Asset>[]),
      ) as _i3.Future<List<_i4.Asset>>);

  @override
  _i3.Future<List<_i5.Location>> loadAndOrganizeData(
    String? locationsPath,
    String? assetsPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadAndOrganizeData,
          [
            locationsPath,
            assetsPath,
          ],
        ),
        returnValue: _i3.Future<List<_i5.Location>>.value(<_i5.Location>[]),
      ) as _i3.Future<List<_i5.Location>>);
}
